### ISSUE TITLE
Dependencies don't install

### ISSUE THREAD

**Issue by digitalduke** [digitalduke/ghreport#10]
It seem that ` packages=find_packages(),` doesn't working.

<details>
<summary>console log</summary>

```
~ $  cd /home/digitalduke/dev
~/dev $  cd /home/digitalduke/dev/env3
~/d/env3 $ virtualenv -p python3 venv
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/digitalduke/dev/env3/venv/bin/python3
Also creating executable in /home/digitalduke/dev/env3/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
~/d/env3 $ source venv/bin/activate.fish
(venv) ~/d/env3 $ pip install -i https://test.pypi.org/simple/ ghreport
Looking in indexes: https://test.pypi.org/simple/
Collecting ghreport
  Downloading https://test-files.pythonhosted.org/packages/79/08/9faa2ab00f615708824508ee7f34504c7bdae8cd377efcbf354faaf7834a/ghreport-0.7-py3-none-any.whl
Installing collected packages: ghreport
Successfully installed ghreport-0.7
(venv) ~/d/env3 $ ghreport 
Traceback (most recent call last):
  File "/home/digitalduke/dev/env3/venv/bin/ghreport", line 6, in <module>
    from ghreport.ghreport import run
  File "/home/digitalduke/dev/env3/venv/lib/python3.5/site-packages/ghreport/ghreport.py", line 6, in <module>
    from dateutil.parser import parse
ImportError: No module named 'dateutil'

```

</details>

**Comment by digitalduke** [comment]
I am wrong, `packages=find_packages()` it is not about finding and installing dependencies. 

For specifying dependencies there is a key [`install_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#install-requires)

Solved and closed via https://github.com/digitalduke/ghreport/pull/11
